name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: lumos-config-generator
            asset_name: lumos-config-generator-linux-amd64
          - os: windows-latest
            artifact_name: lumos-config-generator.exe
            asset_name: lumos-config-generator-windows-amd64.exe
          - os: macos-latest
            artifact_name: lumos-config-generator
            asset_name: lumos-config-generator-macos-amd64

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
